Shop.Items["Base.Crowbar"] = { tab = Tab.Armi, price = 300}
Shop.Items["SOMWReward.SRewardKnife"] = { tab = Tab.Armi, price = 5000}
Shop.Items["SOMWReward.SRewardCleaver"] = { tab = Tab.Armi, price = 8000}
Shop.Items["SOMWReward.SRewardHammer"] = { tab = Tab.Armi, price = 10000}
Shop.Items["SOMWReward.SRewardHandAxe"] = { tab = Tab.Armi, price = 15000}
Shop.Items["SOMWReward.SRewardBaseballBat"] = { tab = Tab.Armi, price = 20000}
Shop.Items["SOMWReward.SRewardAxe"] = { tab = Tab.Armi, price = 25000}
Shop.Items["SOMWReward.SRewardSpear"] = { tab = Tab.Armi, price = 35000}
Shop.Items["SOMWReward.SRewardMachete"] = { tab = Tab.Armi, price = 35000}
Shop.Items["SOMWReward.SRewardKatana"] = { tab = Tab.Armi, price = 50000}