Shop.Items["Base.ShotgunShellsBox"] = { tab = Tab.Munizioni, price = 100}
Shop.Items["Base.223Box"] = { tab = Tab.Munizioni, price = 100}
Shop.Items["Base.22Box"] = { tab = Tab.Munizioni, price = 100}
Shop.Items["Base.308Box"] = { tab = Tab.Munizioni, price = 100}
Shop.Items["Base.308Box"] = { tab = Tab.Munizioni, price = 100}
Shop.Items["Base.762Box"] = { tab = Tab.Munizioni, price = 100}
Shop.Items["Base.Bullets38Box"] = { tab = Tab.Munizioni, price = 60}
Shop.Items["Base.Bullets44Box"] = { tab = Tab.Munizioni, price = 60}
Shop.Items["Base.Bullets45Box"] = { tab = Tab.Munizioni, price = 60}
Shop.Items["Base.Bullets9mmBox"] = { tab = Tab.Munizioni, price = 60}